### ISSUE TITLE
Photos export fails to work under Sierra 10.12.3.

### ISSUE THREAD

**Issue by erlicthemad** [miyako/4d-plugin-photos-v2#2]
I have discovered that the photos export fails to work under Sierra 10.12.3. with the current version of photos. I will get an error dialog like that for each photo selected.
![screenshot 2017-03-22 11 21 52](https://cloud.githubusercontent.com/assets/868472/24205490/e8d37238-0ef1-11e7-96dd-22843fe85095.png)

When I check my console during the export I get the following errors. 

> Error performing copyPath from file:///Users/username/Pictures/Photos%20Library.photoslibrary/Masters/2017/03/18/20170318-004109/IMG_2252.JPG to /Users/username/Library/Caches/1CC2EC3F-8253-42D2-A7F1-614EFEAB6BC0/IMG_2252.JPG; error: Error Domain=NSOSStatusErrorDomain Code=-1 "kCFStreamErrorHTTPParseFailure / kCFSocketError / kCFStreamErrorDomainCustom / kCSIdentityUnknownAuthorityErr / qErr / telGenericError / dsNoExtsMacsBug / kMovieLoadStateError / cdevGenErr: Could not parse the request/response. /  / custom to the kind of stream in question  /  / queue element not found during deletion /  / not a SysErr, just a placeholder  /  / General error; gray cdev w/o alert"
> 
> SandboxViolation: Photos(9707) deny file-write-create /Users/username/Library/Caches/1CC2EC3F-8253-42D2-A7F1-614EFEAB6BC0
> Violation:       deny file-write-create /Users/username/Library/Caches/1CC2EC3F-8253-42D2-A7F1-614EFEAB6BC0
> Process:         Photos [9707]
> Path:            /Applications/Photos.app/Contents/MacOS/Photos
> Load Address:    0x106958000
> Identifier:      com.apple.Photos
> Version:         3130.0.240 (2.0)
> Code Type:       x86_64 (Native)
> Parent Process:  launchd [1]
> Responsible:     /Applications/Photos.app/Contents/MacOS/Photos [9707]
> User ID:         502
>

From what I am seeing the plugin needs to not use the caches as a temporary destination for the photo transfer, and may need to use another folder instead. The code worked under Sierra 10.12.2 and earlier. but after upgrading to 10.12.3 which is recommended for 4d v15.4 it ceases to work.

Thank you for your efforts in putting together these plugins.

**Comment by miyako** [comment]
I've changed the export path from Caches to Temporary folder ([URLsForDirectory:inDomains:](https://developer.apple.com/reference/foundation/nsfilemanager/1407726-urlsfordirectory?language=objc) + [URLFor​Directory:​in​Domain:​appropriate​For​URL:​create:​error:​](https://developer.apple.com/reference/foundation/nsfilemanager/1407693-urlfordirectory?language=objc)) 

is it better now?

**Comment by erlicthemad** [comment]
I tried to use the plugin and it does not seem to be updated. I tried to use your test DB Photos v2.4dbase and I am still getting errors that it is trying to write to caches. 

`SandboxViolation: Photos(3225) deny file-write-create /Users/user/Library/Caches/EA396242-C0F6-42BA-995A-B396AF14920C
Violation:       deny file-write-create /Users/user/Library/Caches/EA396242-C0F6-42BA-995A-B396AF14920C
Process:         Photos [3225]
Path:            /Applications/Photos.app/Contents/MacOS/Photos`

**Comment by erlicthemad** [comment]
I see you updated the source code but the plugin does not seem to have changed.

**Comment by miyako** [comment]
I am pretty sure the plugin itself is updated 

https://github.com/miyako/4d-plugin-photos-v2/blob/master/photos-v2/Photos%20v2.4dbase/Plugins/Photos%20v2.bundle/Contents/MacOS/Photos%20v2

what makes you think the plugin is not changed?

**Comment by erlicthemad** [comment]
THe plugin is still giving me the same issues. I dropped the spefified file into the plugin in you demo database and ran the database under 4d v15.4 32 bit. When I run method1 I get the same errors. 

Screenshot 2017-04-02 08.44.08

```
SandboxViolation: Photos(71275) deny file-write-create /Users/user/Library/Caches/44D87428-C580-4A29-84CD-7B7A57531DD5
Violation:       deny file-write-create /Users/user/Library/Caches/44D87428-C580-4A29-84CD-7B7A57531DD5
Process:         Photos [71275]
Path:            /Applications/Photos.app/Contents/MacOS/Photos
Load Address:    0x109b0b000
Identifier:      com.apple.Photos
Version:         3130.0.240 (2.0)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Applications/Photos.app/Contents/MacOS/Photos [71275]
User ID:         502

Date/Time:       2017-04-02 08:51:17.962 EDT
OS Version:      Mac OS X 10.12.3 (16D32)
Report Version:  8

```

I tried both downloading a new copy of the project zipped, and just the plugin code component you specified. I will download a whole new copy of the project and try again. To get the updates I and downloading the zipped version of the project from github.

**Comment by erlicthemad** [comment]
Just to make sure I wasn't missing something. I did the following steps.

1. Download the zipped project to my downloads folder. 
2. Unzipped the folder and put in my Home directory.
3. Opened my ~/Library/Application Support/4D folder and removed the Photos v2 database form the application support folder. Put in trash.
4. Opened my ~/Library/Caches and deleted the 4D folder from there.
5. Emptied Trash
6. Launched my 4D v15r4 32 Bit and opened the Photos v2.4dbase package in the newly unzipped 4d-plugin-photos-v2-master/photos-v2 folder
7. Selected 3 photos from my Photos Application
8. Executed method1 in the open 4D database
9. Received 3 Exports results dialog error boxes then the 4d code returned without changing my clipboard.
10. Also checked and received 3 sandbox violations that the plugin was having photos save the file to the caches folder.

I did try to open the project in xcode but since I do not have your developer certificate it refused to build.

**Comment by erlicthemad** [comment]
I am not trying to be mean, I am just trying to be thorough in my steps and checking. I dont want to have missed something in the downloaded plugin.

**Comment by miyako** [comment]
I appreciate your feedback, the specifics does matter. what you describe suggests that the plugin was updated but the change didn't solve you problem, which is a useful piece of information.



宮古　啓介
テクニカルアカウントマネージャー


株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/jp

**Comment by erlicthemad** [comment]
I have just upgraded to Mac OS 10.12.4 and still using 4D v15.4. I downloaded a zip of your GitHub library as a zip file and found that the plugin now works in my dev server. My dev server is a 4D v15.4 server connecting with a 4D v15.4 client.  I will next week try it on my production server. But the things you changed under 10.12.4 seem to work well.

**Comment by miyako** [comment]
That's good to know, thank you for the update!
