### ISSUE TITLE
Synchronous import not getting photos.

### ISSUE THREAD

**Issue by erlicthemad** [miyako/4d-plugin-photos-v2#3]
When I try to import synchronously it does not seem to be working. The function returns the names, dates, and ids, in an array, but the photos array returns empty. I have tried this with both process and local variables.

When performed asynchronously the function works fine.

**Comment by miyako** [comment]
I've updated the sync method to use the same logic for temp paths

**Comment by erlicthemad** [comment]
On Monday  May 15, I will be back in the office for the job and will test the updates. Ill let you know how it goes.
