### ISSUE TITLE
Plugin fails to work under 4D V17r4.

### ISSUE THREAD

**Issue by erlicthemad** [miyako/4d-plugin-photos-v2#5]
I am working with the new 4D V17r4 beta and am finding that the plugin is now failing to work. Specifically, it does not appear that the callback is being called with the photos in the selection of the Photos.app ate being honored. I know it works under v16r6 with 10.14.3 but under 17r4 is will not.

**Comment by miyako** [comment]
it sounds like a side effect of tightened automation restrictions of Mojave.

c.f. 

https://github.com/miyako/4d-plugin-notes
https://github.com/miyako/4d-utility-build-application

**Comment by miyako** [comment]
I have added code to request automation permissions for Mojave. 
But you need to sign your app (4D or Unlimited Desktop) yourself.

**Comment by erlicthemad** [comment]
Question. 
	Does this mean that is I just run the 4D app I will have to get an Apple developer membership and sign the plugin myself?

**Comment by miyako** [comment]
that is right, the signature must be performed on the app, not the plugin.

but you can create a free apple developer account to codesign, and use utility-build-application tool to sign it. 

it is super easy.

**Comment by erlicthemad** [comment]
Where is this developer account info? All I can see is the $99 and $299 accounts. If there was a free program that gave me code signing certificates I would be on that in a heartbeat.

**Comment by miyako** [comment]
basically, you create an Apple ID (if you don't have one already),
go to developer.apple.com and agree to terms.
go back to Xcode, login, 
Preferences > Accounts > Add 
Preferences > Accounts > Manage Certificates > Add
